#pragma once
namespace KEngine {
	enum KEnum {
		UNDEFINED,
		RASTR_CULLBACKFACE,
		SHADERTYPE_VERTEX,
		SHADERTYPE_FRAGMENT,
			
		MESH_SPONZA,
		MESH_CONE,
		MESH_CYLINDER,
		MESH_CUBE,
		MESH_HELIX,
		MESH_SPHERE,
		MESH_TORUS,
		MESH_PLANE,
		MESH_FRUSTUM,
		MESH_SPOTLIGHT,

		SHADER_SIMPLE,

		RENDER_FORWARD_ATLAS_CLUSTERED_FRUSTUM,
		RENDER_WORLD_POSITION,

		RENDER_DEFAULT,
		RENDER_WORLD_DIFFUSE_NORMAL_PROPERTY,
		RENDER_WORLD,
		RENDER_SKYBOX,
		RENDER_DIRECT_LIGHT,
		RENDER_LIGHT_SHAFT,
		RENDER_LIGHT_ATLAS,
		RENDER_SKYBOX_REFLECTION,
		RENDER_FRUSTUM_INSIDE,
		RENDER_ONE_COLOR,
		RENDER_TRANSPARENT,
		RENDER_SPHERICAL_HARMONIC_DIFFUSE_MAP,


		TEXTURE_SKYBOX_SUNNY,

		TEXTURE_DEFAULT,
		TEXTURE_NORMAL_DEFAULT,

		TXTURE_ROCK_ALBD,
		TXTURE_ROCK_AO,
		TXTURE_ROCK_HEIGHT,
		TXTURE_ROCK_METALNESS,
		TXTURE_ROCK_NORMAL,
		TXTURE_ROCK_ROUGH,

		TEXTURE_HEIGHT_DEFAULT,
		TEXTURE_HEIGHT_BUMP,
		TEXTURE_HEIGHT_CLOUD,
		TEXTURE_HEIGHT_CIRCLES,

		TEXTURE_ICN_LIGHT,
		TEXTURE_WHITE,
		TEXTURE_RED,
		TEXTURE_PROBE0,

		TEXTURETYPE_DEFAULT,
		TEXTURETYPE_DIFFUSE,
		TEXTURETYPE_NORMAL,
		TEXTURETYPE_PROPERTY,
		TEXTURETYPE_DISPLACEMENT,
		TEXTURETYPE_SPECULAR,

		TEXTURE_WORLD,
		TEXTURE_NORMAL,
		TEXTURE_DIFFUSE,
		TEXTURE_PROPERTY,
		TEXTURE_LIGHT_ATLAS,
		TEXTURE_LIGHTSHAFT_FRONT,
		TEXTURE_LIGHTSHAFT_BACK,
		TEXTURE_FINAL,
		TEXTURE_TEST,

		DEPTH_WORLD,
		DEPTH_FINAL,
		DEPTH_LIGHT_ATLAS,
		DEPTH_LIGHTSHAFT_FRONT,
		DEPTH_LIGHTSHAFT_BACK,
		DEPTH_TEST,

		SAMPLER_WRAP,
		SAMPLER_POINT,
		SAMPLER_CLAMP,
		SAMPLER_BORDER_ONE,
		SAMPLER_BORDER_ZERO,
		SAMPLER_LINEAR,


	};
	KEnum getRadnomModelID();
}